include ':tio-account'
include ':tio-verification'
include ':tio-social'
include ':lib-social'
include ':lib-qrcode'
include ':pay-ease'
include ':common-silent'
include ':jpush'
include ':lib-wallet'
include ':lib-appupdate'
include ':lib-androidutils'
include ':lib-db'
include ':lib-audiorecord'
include ':lib-imclient'
include ':lib-httpclient'
include ':lib-webrtclib'
include ':pullToRefershLibraryMy'
include ':app'
include ':easyPhotos'
include ':lib-baseRecyclerView'

rootProject.name = "TioIm-New-UI"
