apply plugin: 'com.android.library'

android {
    compileSdkVersion 29
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 1
        versionName "1.0.0"

        consumerProguardFiles "consumer-rules.pro"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    sourceSets.main {
        jniLibs.srcDir 'libs'
        jni.srcDirs = []
    }
    android.libraryVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "${project.name}-${defaultConfig.versionName}-${buildType.name}.aar"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'

    api 'org.webrtc:google-webrtc:1.0.30039'

    implementation project(path: ':lib-imclient')
    implementation project(path: ':lib-httpclient')
}
